from unittest import TestSuite
from unittest import main as unitTestMain

from codeallybasic.UnitTestBase import UnitTestBase

from pyimage2pdf.PyImage2Pdf import PyImage2Pdf


# import the class you want to test here
# from org.pyut.template import template


class TestPyImage2Pdf(UnitTestBase):
    """
    Auto generated by the one and only:
        Gato Malo – Humberto A. Sanchez II
        Generated: 31 December 2024
    """

    @classmethod
    def setUpClass(cls):
        super().setUpClass()

    def setUp(self):
        super().setUp()

    def tearDown(self):
        super().tearDown()

    def testInstantiation(self):

        pyimage2pdf: PyImage2Pdf = PyImage2Pdf()

        self.assertIsNotNone(pyimage2pdf, 'I should get an instance')


def suite() -> TestSuite:
    import unittest

    testSuite: TestSuite = TestSuite()

    testSuite.addTest(unittest.defaultTestLoader.loadTestsFromTestCase(testCaseClass=TestPyImage2Pdf))

    return testSuite


if __name__ == '__main__':
    unitTestMain()
